version: "3.9"

services:
  todo_server:
#    build: .
    image: snalagoz/todo-app-todo_server:latest
    container_name: todo-backend
    environment:
      COUCHBASE_HOST: db
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - my_network
  db:
#    build: ./couchbase
    image: couchbase/server
    container_name: todo-couchbase
    volumes:
      - ~/couchbase/node1:/opt/couchbase/var
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    networks:
      - my_network

networks:
  my_network:
    driver: bridge